# Generated by Django 3.0.6 on 2020-05-27 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=300)),
                ('answer', models.ManyToManyField(to='exam.answer')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.genre')),
                ('option', models.ManyToManyField(related_name='option', to='exam.answer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.type')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('logtime', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.interviewee')),
                ('quiz', models.ManyToManyField(to='exam.quiz')),
                ('userAnswer', models.ManyToManyField(to='exam.answer')),
            ],
        ),
    ]
