# Generated by Django 3.0.6 on 2020-05-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200527_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='userAnswer',
        ),
        migrations.AddField(
            model_name='exam',
            name='userAnswer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
