# Generated by Django 3.0.6 on 2020-05-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200527_1506'),
    ]

    operations = [
    ]
