# Generated by Django 3.0.6 on 2020-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200527_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='userAnswer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
