# Generated by Django 3.0.6 on 2020-05-29 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200529_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 10, 7, 27, 329483), null=True),
        ),
    ]
