# Generated by Django 3.0.6 on 2020-05-29 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200529_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='finishTime',
            new_name='endTime',
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 11, 30, 42, 759040), null=True),
        ),
    ]
