# Generated by Django 3.0.6 on 2020-06-03 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20200601_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allowIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 12, 58, 16, 776170)),
        ),
    ]
