# Generated by Django 3.0.6 on 2020-06-04 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20200603_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quizNum',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 38, 31, 305505)),
        ),
    ]
