# Generated by Django 3.0.6 on 2020-06-04 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20200604_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='interviewee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 15, 21, 11, 459595)),
        ),
    ]
