# Generated by Django 3.0.6 on 2020-06-04 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20200604_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 23, 49, 54, 570968, tzinfo=utc)),
        ),
    ]
