# Generated by Django 3.0.6 on 2020-06-05 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20200605_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 5, 5, 3, 117097, tzinfo=utc)),
        ),
    ]
