# Generated by Django 3.0.6 on 2020-06-19 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20200605_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='logtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=3000),
        ),
    ]
